import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from "@clerk/nextjs";


// Load local fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata for the page
export const metadata: Metadata = {
  title: "Car Rent",
  description: "Generated by create next app",
}


// RootLayout component
export default function RootLayout({
  children,
  hideLayout = false, // Default: Show layout
}: {
  children: React.ReactNode;
  hideLayout?: boolean;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="absolute top-7 right-4">
          {/* Authentication Section */}
          
          <SignedOut>
            <SignInButton mode="modal">
              <div >
              <button className="relative overflow-hidden h-12 px-8 rounded-3xl bg-[#3563e9] text-white border-none cursor-pointer group">
  <span className="relative bottom-1 z-10">Sign In </span>
  <span className="absolute inset-0 scale-x-0 bg-gradient-to-r from-[#000000] to-[#080808] transition-transform duration-[0.475s] origin-left rounded-3xl group-hover:scale-x-100"></span>
        </button>
              </div>
            </SignInButton>
          </SignedOut>
          <SignedIn>
            <UserButton showName />
          
          </SignedIn>
</div>
          {/* Show Navbar & Footer only if hideLayout is false */}
          {!hideLayout && <Navbar />}
          <main>{children}</main>
          {!hideLayout && <Footer />}
        </body>
      </html>
    </ClerkProvider>
  );
}
